name: dead_code_analyzer
description: A tool to analyze and identify dead/unused code in Dart and Flutter projects.
version: 0.1.1
homepage: https://github.com/jaypal1046/dead_code_analyzer
repository: https://github.com/jaypal1046/dead_code_analyzer
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  path: ^1.8.0
  args: ^2.4.0 # For command-line argument parsing
  intl: ^0.17.0 # For internationalization
  analyzer: ^6.4.1
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  dead_code_analyzer: dead_code_analyzer